name: Promote Image

on: 
  pull_request_review:
    types:
      - submitted

jobs:
  promote-image:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'development'
    runs-on: ubuntu-latest
    
    steps:
        
      - name: Login to GitHub Container Registry
      
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull PR image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/web_app:${{ github.event.pull_request.head.sha }}-pr

      - name: Retag approved image
        run: |
          docker tag \
          ghcr.io/${{ github.repository_owner }}/web_app:${{ github.event.pull_request.head.sha }}-pr \
          ghcr.io/${{ github.repository_owner }}/web_app:${{ github.event.pull_request.head.sha }}

      - name: Push approved image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/web_app:${{ github.event.pull_request.head.sha }}

      - name: Merge PR into development branch
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    
